[package]
name = "server_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reload = { path = "../reload/" }
derive_builder = "0.12.0"
anyhow = "1.0.71"
thiserror = "1.0.40"
tokio = { version = "1.29.1", features = [
  "net",
  "rt-multi-thread",
  "parking_lot",
  "time",
  "sync",
  "macros",
] }
tracing = "0.1.37"
